#!/bin/bash

rm -f tests/test[0-9]*.c

for i in `seq 1 $3`;
do
	java -jar PSTL.jar $1 $2 &>tests/test$i.c
	json_res=`mopsa-c tests/test$i.c -format=json`
	grep_res=`grep -n "erreur ici" tests/test$i.c | cut -d':' -f1 `
	python3 error_checker.py $1 "test$i.c" $grep_res $json_res
done
