package enums;

public enum ErrorType {
	OUT_OF_BOUNDS(1), NULL_POINTER_DEREFERENCE(2), INVALID_POINTER_DEREFERENCE(3),
	DIVISION_BY_ZERO(4), INTEGER_OVERFLOW(5), ILLEGAL_POINTER_DIFFERENCE(6),
	ILLEGAL_POINTER_COMPARISON(7), USE_AFTER_FREE(8), DOUBLE_FREE(9),
	NO_NEXT_ARG_FOR_va_arg(10), INVALID_BIT_SHIFT(11), MODIFICATION_OF_READONLY_MEMORY(12),
	DANGLING_POINTER_DEREFERENCE(13), INSUFFICIENT_NUMBER_FORMAT_ARGUMENT(14), INCORRECT_TYPE_FORMAT_ARGUMENT(15);
	
	public final int num;
	
	private ErrorType(int num) {
		this.num = num;
		
	}
}
